import { useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { useAnnouncements } from "@/contexts/AnnouncementsContext";
import { ArrowLeft, Bookmark, BookmarkCheck, Pin, Paperclip, Eye, Calendar, Clock, FileText, Download } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";

export default function AnnouncementDetail({ basePath = "/user" }: { basePath?: string }) {
  const { id } = useParams<{ id: string }>();
  const { announcements, toggleBookmark, markAsRead } = useAnnouncements();
  const { user } = useAuth();
  const a = announcements.find((ann) => ann.id === id);

  useEffect(() => {
    if (a) {
      document.title = `${a.title} – Smart Campus`;
      markAsRead(a.id);
    }
  }, [a?.id]);

  if (!a) {
    return (
      <div className="text-center py-16">
        <p className="text-muted-foreground">Announcement not found</p>
        <Link to={basePath} className="text-primary text-sm mt-2 inline-block hover:underline">Back to dashboard</Link>
      </div>
    );
  }

  const priorityMap = {
    high: "bg-priority-high",
    normal: "bg-priority-normal",
    low: "bg-priority-low",
  };

  const handleDownloadPDF = () => {
    const content = `
SMART CAMPUS ANNOUNCEMENT SYSTEM
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${a.title}

Department: ${a.department}
Category: ${a.category}
Priority: ${a.priority.toUpperCase()}
Published: ${a.createdAt}
Expires: ${a.expiryDate}
Status: ${a.status}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${a.description}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Smart Campus Announcement System
© 2026 Smart Campus. All rights reserved.
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `announcement-${a.id}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <Link to={basePath} className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors">
        <ArrowLeft className="h-4 w-4" /> Back
      </Link>

      <article className="campus-card-static p-6 sm:p-8 space-y-5 animate-fade-in-up">
        <div className="flex items-center gap-2 flex-wrap">
          {a.pinned && (
            <span className="inline-flex items-center gap-1 text-xs text-campus-blue font-medium"><Pin className="h-3 w-3" /> Pinned</span>
          )}
          <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${priorityMap[a.priority]}`}>
            {a.priority.charAt(0).toUpperCase() + a.priority.slice(1)} Priority
          </span>
          <span className="text-xs px-2 py-0.5 rounded-full bg-campus-olive-light text-campus-olive font-medium">{a.category}</span>
          <span className="text-xs px-2 py-0.5 rounded-full bg-muted text-muted-foreground font-medium">{a.department}</span>
          <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${
            a.status === "Published" ? "bg-campus-olive-light text-campus-olive" :
            a.status === "Rejected" ? "bg-priority-high" :
            "bg-priority-normal"
          }`}>{a.status}</span>
        </div>

        <h1 className="text-xl sm:text-2xl font-bold leading-tight">{a.title}</h1>

        <div className="flex items-center gap-4 text-sm text-muted-foreground flex-wrap">
          <span className="inline-flex items-center gap-1"><Calendar className="h-3.5 w-3.5" /> Posted: {a.createdAt}</span>
          <span className="inline-flex items-center gap-1"><Clock className="h-3.5 w-3.5" /> Expires: {a.expiryDate}</span>
          <span className="inline-flex items-center gap-1"><Eye className="h-3.5 w-3.5" /> {a.views} views</span>
        </div>

        <div className="border-t border-border pt-5">
          <p className="text-sm leading-relaxed whitespace-pre-line">{a.description}</p>
        </div>

        {a.attachment && (
          <div className="border-t border-border pt-5">
            <div className="inline-flex items-center gap-3 px-4 py-3 rounded-lg bg-muted text-sm">
              <FileText className="h-5 w-5 text-muted-foreground" />
              <div>
                <p className="font-medium">{a.attachment.name}</p>
                <p className="text-xs text-muted-foreground">{a.attachment.type.toUpperCase()} {a.attachment.size && `• ${a.attachment.size}`}</p>
              </div>
              <button className="ml-2 p-1.5 rounded-md hover:bg-background transition-colors" aria-label="Download">
                <Download className="h-4 w-4 text-primary" />
              </button>
            </div>
          </div>
        )}

        {a.rejectionReason && (
          <div className="border-t border-border pt-5">
            <div className="p-4 rounded-lg bg-destructive/10 text-sm">
              <p className="font-medium text-destructive mb-1">Rejection Reason</p>
              <p className="text-muted-foreground">{a.rejectionReason}</p>
            </div>
          </div>
        )}

        <div className="border-t border-border pt-5 flex items-center gap-3 flex-wrap">
          {user?.role === "user" && (
            <button onClick={() => toggleBookmark(a.id)}
              className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg border border-border text-sm font-medium hover:bg-muted transition-all duration-150">
              {a.isBookmarked ? <><BookmarkCheck className="h-4 w-4 text-primary" /> Bookmarked</> : <><Bookmark className="h-4 w-4" /> Bookmark</>}
            </button>
          )}
          <button onClick={handleDownloadPDF}
            className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg border border-border text-sm font-medium hover:bg-muted transition-all duration-150">
            <Download className="h-4 w-4" /> Download PDF
          </button>
        </div>

        {/* Comments */}
        {a.comments && a.comments.length > 0 && (
          <div className="border-t border-border pt-5">
            <h3 className="text-sm font-semibold mb-3">Discussion</h3>
            <div className="space-y-3">
              {a.comments.map((c) => (
                <div key={c.id} className="p-3 rounded-lg bg-muted/50">
                  <div className="flex items-center gap-2 mb-1">
                    <div className="h-6 w-6 rounded-full bg-primary/10 text-primary text-xs font-bold flex items-center justify-center">
                      {c.author.charAt(0)}
                    </div>
                    <span className="text-sm font-medium">{c.author}</span>
                    <span className="text-xs text-muted-foreground">{c.role}</span>
                    <span className="text-xs text-muted-foreground ml-auto">{new Date(c.timestamp).toLocaleDateString()}</span>
                  </div>
                  <p className="text-sm text-muted-foreground ml-8">{c.text}</p>
                  {c.replies?.map((r) => (
                    <div key={r.id} className="ml-8 mt-2 p-2 rounded-lg bg-muted/50">
                      <div className="flex items-center gap-2 mb-1">
                        <div className="h-5 w-5 rounded-full bg-primary/10 text-primary text-[10px] font-bold flex items-center justify-center">
                          {r.author.charAt(0)}
                        </div>
                        <span className="text-xs font-medium">{r.author}</span>
                        <span className="text-xs text-muted-foreground">{new Date(r.timestamp).toLocaleDateString()}</span>
                      </div>
                      <p className="text-xs text-muted-foreground ml-7">{r.text}</p>
                    </div>
                  ))}
                </div>
              ))}
            </div>
          </div>
        )}
      </article>
    </div>
  );
}
